vehicle:
  name: r1
  class_name: f1tenth-car

  definition_file: ../definitions/f1tenth.xml
  definition_attributes:
    default_sensors: false

  sensors:
    - file: ../definitions/lidar2d.sensor.xml
      attributes:
        sensor_x: 0.4
        sensor_z: 0.2709
        sensor_yaw: 0
        max_range: 30.0
        sensor_name: laser1

    - file: ../definitions/rgbd_camera.sensor.xml
      attributes:
        sensor_x: 0.45
        sensor_z: 0.2409
        sensor_period_sec: 0.03
        show_3d_pointcloud: false

    - file: /opt/ros/humble/share/mvsim/definitions/imu.sensor.xml
      attributes:
        sensor_x: 0.0
        sensor_y: 0.0
        sensor_z: 0.15
        sensor_period_sec: 0.02
        sensor_name: imu1
        sensor_publish: true
        sensor_custom_visual: false
        sensor_angular_velocity_white_noise_std_noise: 2.0e-4
        sensor_linear_acceleration_white_noise_std_noise: 0.017
        sensor_angular_velocity_random_walk_std_noise: 1.0e-5
        sensor_linear_acceleration_random_walk_std_noise: 0
